<?php
/**
* Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

?>
<?php
// @codingStandardsIgnoreFile
/** @var \Magedelight\Subscribenow\Block\Catalog\Product $block */
?>
<?php
$product = $this->getProduct();
$name = $product->getName();
?>
<?php if ($product->getData('is_subscription') == 1): ?>
<strong class="product name product-item-name md-is-subscription" style="margin-bottom: 13px; display:none;">
        <a href="<?php echo $product->getProductUrl(); ?>#md_subscription_content" class="product-item-link" title="<?php echo $block->getSubscriptionText() ?>"><?php echo $block->getSubscriptionText() ?> </a>
    </strong>
<?php endif; ?>
