<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($block->isContentMode() || $block->isMixedMode()): ?>
    <div class="category-cms col-xs-12 col-sm-12 col-md-6 col-lg-6 pull-left">
        <?php echo $block->getCmsBlockHtml(); ?>
    </div>
<?php endif; ?>
