/*Custom CSS*/

.footer ul li {
    width: 100%;
    background: #dc2441;
    font-size: 1.6rem;
    border-top: 1px solid #cecece;
    margin: 0 -15px;
    padding: 0 15px;
}
.footer .links a {
    color: rgba(255,255,255,0.75);
    text-decoration: none;
    padding: 10px 0;
    font-size: 16px;
    text-transform: uppercase;
    font-family: 'futura-pt',Futura,Trebuchet MS,Arial,sans-serif;
    font-weight: 700;
}
.footer ul li:last-child {
    background: none;
}

.amp-logo-container {
    width: 50%;
    margin: 0 0 0 20%;
}

//.mobile-menu:before {
//    color: #FF0000;
//}
.mobile-menu:hover:before {
    color: #636363;
}

.footer address {
    text-transform: uppercase;
    text-align: center;
    color: rgba(255,255,255,0.75);
    font-size: 10px;
    width: 100%;
    border-top: none;
}
.footer-container {
    height: auto;
    background-color: #ef555a;
    width: 100%;
    background-size: 210px 285px,652px 217px;
    clear: both;
    float: none;
    padding: 0;
}
.footer {
    padding-top: 0;
}
body {
    font-family: 'futura-pt',Futura,Trebuchet MS,Arial,sans-serif;
}
.amp-home-promotional-msg {
    font-weight: 700;
    text-transform: uppercase;
    color: #512c1d;
    font-size: 15px;
    text-align: center;
    clear: both;
}
.amp_sheamoisture_footer_oes {
    float: left;
    margin: 0 15px 0 15px;
}
.amp_sheamoisture_footer_oes .sheamoisture_footer_oes-col {
    float: left;
    width: 20%;
    margin: 0;
    padding: 0;
    line-height: 0;
}
.amp_sheamoisture_footer_oes .sheamoisture_footer_oes-col img{
    float: left;
    width: 100%;
    max-width: 15%;
    min-width: 15%;
    margin: 0;
}
.block-search .search {
    width: 100%;
    float: left;
    margin: 0 0 10px 0;
}
.block-search .actions {
    width: 20%;
    float: left;
}
.newsletter_jtf input[type="email"], .block-search input[type="text"] {
    background: #fff;
    background-clip: padding-box;
    border: 1px solid #c2c2c2;
    border-radius: 1px;
    font-family: 'futura-pt',Futura,Trebuchet MS,Arial,sans-serif;
    font-size: 14px;
    height: 32px;
    line-height: 1.42857143;
    padding: 0 9px;
    vertical-align: baseline;
    width: 100%;
    box-sizing: border-box;
}

//@font-face {
//font-family:shoppingBag;
//src: url(<?php echo $this->getAmpSkinUrl('Plumrocket_Amp::fonts/shopping-bag.svg') ?>) format('svg');
//  font-weight: normal;
//  font-style: normal;
//}

.top-shopping-cart {
    background-image: url(<?php echo $this->getAmpSkinUrl('Plumrocket_Amp::images/shopping-bag.png') ?>);
    background-repeat: no-repeat;
    background-position: center center;
    background-size: contain;
}
.newsletter-bottom-block {
    text-align: center;
    padding: 1%;
    color: #512c1d;
    font-size: 14px;
}
.newsletter-bottom-block .newsletter_jtf{
    display: inline-block;
    margin-top: 0px;
    width: 80%;
    margin: 2% 9%;
}
.newsletter-bottom-block .newsletter_jtf .newsletter {
    width: 80%;
    float: left;
}
.newsletter-bottom-block .newsletter_jtf .actions {
    width: 20%;
    float: left;
}
.newsletter-bottom-block .newsletter_jtf .actions .submit-newsletter-footer {
    padding: 6px 15px;
    background-color: #ef555a;
    color: #fff;
    border: 0;
    text-align: center;
    font-weight: 600;
    box-sizing: border-box;
    vertical-align: middle;
    transition: color .25s ease-in-out,background-color .25s ease-in-out;
    border-radius: 3px;
    text-transform: uppercase;
}

