<?php
/**
* Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

?>
<a href="<?php echo $block->getEditUrl(); ?>" title="<?php echo __('Update Profile') ?>">
    <button type="button" title="<?php echo __('Update Profile') ?>" class="action primary add">
        <span><?php echo __('Update Profile') ?></span>
    </button>
</a>