<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php endforeach;?>
		</div>
    </div>
<?php endif; ?>
<script>
    require([
        'jquery'
    ], function($){
		'use strict'; 
            $(document).ready(function(){
            setTimeout(function(){ 
                //$('.data.item.title').removeClass('active');
               // $('#tab-label-product.info.description').addClass('active');
//                 $('.data.item.content').css('display','none');
             }, 500);
            $("#select_1 option:contains('One Time')").attr("selected", "selected");
            $('.data.switch').on('click', function(e){
                e.preventDefault();
                //debugger;
                if ($(this).parent().hasClass('active')){ 
                     $('.data.item.title').removeClass('active');
                     $('.data.item.content').slideUp();
                } else {
                    var getHref = $(this).attr('href');
                    getHref.slice( 1 );
                   $(this).parent().addClass('active');
                   $('#'+getHref).slideDown();
                }
                e.stopPropagation();
            });
		    
        /* select first option for custom options */
		if ($(".product-options-wrapper option:first").val() != "") {
			$(".product-options-wrapper option:first").attr('selected','selected');
		} else {
			$(".product-options-wrapper option:eq(1)").attr('selected','selected');
		}
    
        }); 
        
    });
</script>
