<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php 
            $i = 0;
            foreach ($detailedInfoGroup as $name):

                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title<?php echo ($i == 0) ? ' active' : ''; ?>"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias; ?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="<?php echo $i; ?>"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" <?php echo ($i == 0) ? '' : 'style="display:none"'; ?> data-role="content">
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php endforeach;?>
			<!-- Start For Ask a Question Block -->
<!-- 				<div class="data item title" -->
<!--                      aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo 'ask';?>-title" -->
<!--                      data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo 'ask';?>"> -->
<!--                     <a class="data switch" -->
<!--                        tabindex="-1" -->
<!--                        data-toggle="switch" -->
<!--                        href="#<?php /* @escapeNotVerified */ echo 'ask'; ?>" -->
<!--                        id="tab-label-<?php /* @escapeNotVerified */ echo 'ask';?>-title"> -->
                        <?php /* @escapeNotVerified */ //echo 'Ask a Question'; ?>
<!--                     </a> -->
<!--                 </div> -->
<!--                 <div class="data item content" id="<?php /* @escapeNotVerified */ echo 'ask'; ?>" data-role="content"> -->
                    <?php /* @escapeNotVerified */ //echo "Ask a Question"; ?>
<!--                 </div> -->
		<!-- End For Ask a Question Block -->
        </div>
    </div>
<?php endif; ?>
<script>
    require([
        'jquery'
    ], function($){
		'use strict'; 
            $(document).ready(function(){
//             setTimeout(function(){ 
//                 $('.data.item.title').removeClass('active');
//                 $('.data.item.content').css('display','none');
//              }, 500);
            
            $('.data.switch').on('click', function(e){
                e.preventDefault();
                //debugger;
                if ($(this).parent().hasClass('active')){ 
                     $('.data.item.title').removeClass('active');
                     $('.data.item.content').slideUp();
                } else {
                    var getHref = $(this).attr('href');
                    getHref.slice( 1 );
                   $(this).parent().addClass('active');
                   $('#'+getHref).slideDown();
                }
                e.stopPropagation();
            });
        

    
        }); 
        
    });
</script>
		
