<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php /** echo $block->getReviewsSummaryHtml($block->getProduct(), false, true) */?>
<?php 
$_product = $block->getProduct();
$charityAvailable  = $_product->getResource()->getAttribute('charity_available')->getFrontend()->getValue($_product);
$curls =$block->getUrl('pub/media/wysiwyg');
?>
<?php if ($charityAvailable == "Yes") { ?>
	<div class="communityImg" style="
    clear: both;
">
  <div class="col-lg-2 col-md-2 col-sm-4 col-xs-12 ">
<?php	 echo "<img src=\"".$curls."onsale.png"."\">"; ?>   
      </div>
	<div class="col-lg-2 col-md-2 col-sm-4 col-xs-12 ">	
<?php		echo "<img src=\"".$curls."communitycommercess.png"."\">"; ?>
	</div>
       <div class="col-lg-8 col-md-8 col-sm-4 col-xs-12 ">
      		<h3>Earn X points with purchase</h3>
	  </div>
</div>

  <?php } ?>

