<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
/* @var WeltPixel\OwlCarouselSlider\Helper\Products $helper */
$helper = $this->helper('WeltPixel\OwlCarouselSlider\Helper\Products');
$sliderConfiguration = $helper->getSliderConfiguration($block->getType());
$sliderConfig = json_encode($sliderConfiguration);
$helperCustom = $this->helper('WeltPixel\OwlCarouselSlider\Helper\Custom');
$breakpointConfiguration = $helperCustom->getBreakpointConfiguration();
$breakpoint   = $breakpointConfiguration;
$enableSlider = (array_key_exists('status', $sliderConfiguration) && $sliderConfiguration['status'] == 1) ? true : false ;
?>
<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Upsell Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Upsell Products');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('PRODUCTS YOU MIGHT ALSO LIKE');
            $items = $block->getItemCollection();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    case 'other':
        break;
}
?>

<?php if ($exist):?>

<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
    <?php else: ?>
    <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
        <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
            <?php endif; ?>
            <div class="block-title title">
                <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
            </div>
            <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
                <?php if ($type == 'related' && $canItemsAddToCart): ?>
                    <div class="block-actions">
                        <?php /* @escapeNotVerified */ echo __('Check items to add to the cart or') ?>
                        <button type="button" class="action select" role="select-all"><span><?php /* @escapeNotVerified */ echo __('select all') ?></span></button>
                    </div>
                <?php endif; ?>
                <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
                    <ol class="products list items product-items<?php echo $enableSlider ? ' owl-carousel-products-' . $type : ''; ?>">
                        <?php $product_item = $enableSlider ? '' : ' product-item'; ?>
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php if ($type == 'related' || $type == 'upsell'): ?>
                                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <?php endif; ?>

                            <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                                <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>

                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                    <?php if (!$_item->getRequiredOptions()): ?>
                                        <div class="field choice related">
                                            <input type="checkbox" class="checkbox related" id="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>" name="related_products[]" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
                                            <label class="label" for="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><span><?php /* @escapeNotVerified */ echo __('Add to Bag') ?></span></label>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product actions product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Bag') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Bag') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Bag') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Bag') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>

                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php
                                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                        ?>
                                                        <a href="#" class="action tocompare"
                                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                           data-role="add-to-links"
                                                           title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                    <?php if($enableSlider) : ?>
					<div id="pre-div">
						<div class="cssload-loader">
							<div class="cssload-inner cssload-one"></div>
							<div class="cssload-inner cssload-two"></div>
							<div class="cssload-inner cssload-three"></div>
						</div>
					</div>
					<?php endif; ?>
                </div>
            </div>
        </div>
        <?php endif;?>

    <?php if($enableSlider) : ?>
    <script>
        require(['jquery', 'owl_carousel', 'owl_config' ],
            function ($) {
                var products_type = '<?php echo $type;?>',
                    slider_config = <?php echo $sliderConfig; ?>,
                    
                    carouselElement = $('.owl-carousel-products-' + products_type),

	                windowWidth = $(window).width(),
	                carouselWidth = carouselElement.width(),
	                carouselContainer = carouselWidth + 120,

                    items = ((slider_config.items >= 0 && slider_config.items != null) ? slider_config.items : 2),

	                stagePadding = slider_config.stagePadding != '' ? parseInt(slider_config.stagePadding) : 0,

	                sPBrk_1 = slider_config.stagePadding_brk1 != '' ? parseInt(slider_config.stagePadding_brk1) : 0,
	                sPBrk_2 = slider_config.stagePadding_brk2 != '' ? parseInt(slider_config.stagePadding_brk2) : 0,
	                sPBrk_3 = slider_config.stagePadding_brk3 != '' ? parseInt(slider_config.stagePadding_brk3) : 0,
	                sPBrk_4 = slider_config.stagePadding_brk4 != '' ? parseInt(slider_config.stagePadding_brk4) : 0;

	            carouselElement.owlCarousel({
	                nav                 :parseInt(slider_config.nav) == 1 ? true : false,
	                dots                :parseInt(slider_config.dots) == 1 ? true : false,
	                center              :parseInt(slider_config.center) == 1 ? true : false,
	                items               :items,
	                loop                :parseInt(slider_config.loop) == 1 ? true : false,
	                margin              :parseInt(slider_config.margin) != '' ? parseInt(slider_config.margin) : 0,
	                stagePadding        :parseInt(slider_config.center) == 1 ? 0 : stagePadding,
	                lazyLoad            :parseInt(slider_config.lazyLoad) == 1 ? true : false,
	                autoplay            :parseInt(slider_config.autoplay) == 1 ? true : false,
	                autoplayTimeout     :(slider_config.autoplayTimeout > 0 && slider_config.autoplayTimeout != null) ? parseInt(slider_config.autoplayTimeout) : 3000,
	                autoplayHoverPause  :parseInt(slider_config.autoplayHoverPause) == 1 ? true : false,
	                autoHeight          :false,


	                responsive:{
	                    <?php echo $breakpoint['breakpoint_1']; ?>:{
	                        nav             :parseInt(slider_config.nav_brk1) == 1 ? true : false,
	                        items           :(slider_config.items_brk1  >= 0 && slider_config.items_brk1 != null) ? parseInt(slider_config.items_brk1) : items,
	                        center          :parseInt(slider_config.center_brk1) == 1 ? true : false,
	                        stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_1,
	                    },
	                    <?php echo $breakpoint['breakpoint_2']; ?>:{
	                        nav             :parseInt(slider_config.nav_brk2) == 1 ? true : false,
	                        items           :(slider_config.items_brk2  >= 0 && slider_config.items_brk2 != null) ? parseInt(slider_config.items_brk2) : items,
	                        center          :parseInt(slider_config.center_brk2) == 1 ? true : false,
	                        stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_2,
	                    },
	                    <?php echo $breakpoint['breakpoint_3']; ?>:{
	                        nav             :parseInt(slider_config.nav_brk3) == 1 ? true : false,
	                        items           :(slider_config.items_brk3  >= 0 && slider_config.items_brk3 != null) ? parseInt(slider_config.items_brk3) : items,
	                        center          :parseInt(slider_config.center_brk3) == 1 ? true : false,
	                        stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_3,
	                    },
	                    <?php echo $breakpoint['breakpoint_4']; ?>:{
	                        nav             :parseInt(slider_config.nav_brk4) == 1 ? true : false,
	                        items           :(slider_config.items_brk4  >= 0 && slider_config.items_brk4 != null) ? parseInt(slider_config.items_brk4) : items,
	                        center          :parseInt(slider_config.center_brk4) == 1 ? true : false,
	                        stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_4,
	                    }
	                }
	            });

                var carouselControls = carouselElement.find('.owl-nav');
	            if (carouselContainer >= windowWidth) {
	                carouselControls.find('.owl-prev').css({
	                    'left': 0,
	                  });
	                carouselControls.find('.owl-next').css({
	                    'right': 0,
	                });
	            }
            });
    </script>
    <?php endif;?>