<?php
/**
 * Copyright © 2015 MangoExtensions. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder" id="quickview-gallery-placeholder">
    <div data-role="loader" class="loading-mask">
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...') ?>">
        </div>
    </div>
</div>
<script type="text/javascript">

    require(["mage/gallery/gallery", 'magnifier/magnify'], function (QuickviewGallery, QuickviewMagnifier) {
        return new QuickviewGallery(
                QuickviewMagnifier(
                        {
                            "magnifierOpts": <?php /* @escapeNotVerified */ echo $block->getMagnifier(); ?>,
                            "data": <?php /* @escapeNotVerified */ echo $block->getGalleryImagesJson(); ?>,
                            "options": {
                                "nav": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/nav"); ?>",
                                "loop": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/loop"); ?>,
                                "keyboard": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/keyboard"); ?>,
                                "arrows": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/arrows"); ?>,
                                "allowfullscreen": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/allowfullscreen"); ?>,
                                "showCaption": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/caption"); ?>,
                                "width": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                                "thumbwidth": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                                "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height') ? : $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                                "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height') ? : $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                                "transitionduration": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/transition/duration"); ?>,
                                "transition": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/transition/effect"); ?>",
                                "navarrows": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/navarrows"); ?>,
                                "navtype": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/navtype"); ?>",
                                "navdir": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/navdir"); ?>"
                            },
                            "fullscreen": {
                                "nav": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/fullscreen/nav"); ?>",
                                "loop": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/fullscreen/loop"); ?>,
                                "navdir": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/fullscreen/navdir"); ?>",
                                "arrows": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/fullscreen/arrows"); ?>,
                                "showCaption": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/fullscreen/caption"); ?>,
                                "transitionduration": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/fullscreen/transition/duration"); ?>,
                                "transition": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/fullscreen/transition/effect"); ?>"
                            },
                            "breakpoints": <?php /* @escapeNotVerified */ echo $block->getBreakpoints(); ?>


                        }, "#quickview-gallery-placeholder")
                , "#quickview-gallery-placeholder");
    });
	require(['jquery', 'jquery/ui'], function($){ 
		$('#buy-now').click(function () {
			$(this).attr("disabled", true);
			var form = $(".product-add-form form");
			var widget = form.catalogAddToCart({
					bindSubmit: false
				});

			// change form action
			var baseUrl = form.attr('action'),
				buyNowUrl = baseUrl.replace('checkout/cart/add', 'buynow/cart/add');

			form.attr('action', buyNowUrl);
			widget.catalogAddToCart('submitForm', form);

			// set form action back
			form.attr('action', baseUrl);
		});
	});
</script>
