<?php
/**
* Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

?>
<?php
// @codingStandardsIgnoreFile
?>
<?php
$subscriptionProfiles = $block->getSubscriptionProfiles();
if (empty($subscriptionProfiles)) {
    return;
}
$subscriptionProfiles = explode(",", $subscriptionProfiles);
?>
<?php if (!empty($subscriptionProfiles)): ?>
    <div class="subscription-success" style="margin-top: 2%">
        <p><?php echo __('Your subscription payment profiles:') ?></p>
        <?php foreach ($subscriptionProfiles as $subscriptionProfile) : ?>
            <p><?php echo __('Your subscription profile number is: %1.', sprintf('<a href="%s" class="subscription-number"><strong>%s</strong></a>', $block->escapeHtml($block->getSubscriptionUrl($subscriptionProfile)), $block->escapeHtml($block->getProfileIdFromId($subscriptionProfile)))) ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>